### ISSUE TITLE
Click events on NFT wallet view

### ISSUE THREAD

**Issue by wtracy** [covalenthq/goldrush-kit#162]
Right now, I don't a way to register click events on the NFT wallet component without actually modifying the component code. Am I reading this right?

If I wanted to add click event support and have the change merged back, does the team have any strong opinions on how this should be implemented?

**Comment by jagnani73** [comment]
You are reading this right, we are working on adding click functions to the Organisms

There aren't any strong opinions if you want to contribute to the code. You can refer to [this](https://github.com/covalenthq/goldrush-kit/blob/ea7351f2135cf3fe929aded28389c36c53ac2e1d/src/components/Organisms/NFTs/NFTCollectionTokenListView/NFTCollectionTokenListView.tsx#L195) and how this is implemented.

There are tests for proper linting that need to be passed before merging the code and thats it!

**Comment by jagnani73** [comment]
Hey @wtracy 
This feature is added, you can use `actionable`s like in the [https://goldrush-kit.vercel.app/?path=/story/organisms-nft-collection-view--nft-collection-view](urlstorybook

**Comment by wtracy** [comment]
Thanks!

I have it working with my local copy, and haven't had a chance to get it
cleaned up and submit a pull request.

William
